package lintconfig

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestGenerate_StandardPreset(t *testing.T) {
	t.Parallel()

	catalog, err := LoadCatalog()
	if err != nil {
		t.Fatalf("LoadCatalog: %v", err)
	}

	data, err := Generate(catalog, GenerateOptions{
		GoVersion:   "1.26.1",
		LintVersion: "v2.11.2",
		Preset:      PresetStandard,
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(data)
	if !strings.Contains(output, "version: \"2\"") {
		t.Fatal("expected version: \"2\" in output")
	}
	if !strings.Contains(output, "govet") {
		t.Fatal("expected govet in output")
	}
	if !strings.Contains(output, "default: none") {
		t.Fatal("expected default: none in output")
	}
	if strings.Contains(output, "formatters") {
		t.Fatal("formatters section should not be present without --with-imports")
	}
}

func TestGenerate_WithImports(t *testing.T) {
	t.Parallel()

	catalog, err := LoadCatalog()
	if err != nil {
		t.Fatalf("LoadCatalog: %v", err)
	}

	data, err := Generate(catalog, GenerateOptions{
		GoVersion:   "1.26.1",
		LintVersion: "v2.11.2",
		Preset:      PresetStandard,
		WithImports: true,
		ModulePath:  "github.com/example/myproject",
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(data)
	if !strings.Contains(output, "formatters") {
		t.Fatal("expected formatters section with --with-imports")
	}
	if !strings.Contains(output, "gci") {
		t.Fatal("expected gci in formatters")
	}
	if !strings.Contains(output, "prefix(github.com/example/myproject)") {
		t.Fatal("expected module path in gci sections")
	}
}

func TestGenerate_ValidYAML(t *testing.T) {
	t.Parallel()

	catalog, err := LoadCatalog()
	if err != nil {
		t.Fatalf("LoadCatalog: %v", err)
	}

	data, err := Generate(catalog, GenerateOptions{
		GoVersion:   "1.26.1",
		LintVersion: "v2.11.2",
		Preset:      PresetStrict,
		WithImports: true,
		ModulePath:  "github.com/example/test",
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// Strip comment lines before parsing.
	lines := strings.Split(string(data), "\n")
	var yamlLines []string
	for _, line := range lines {
		if !strings.HasPrefix(line, "#") {
			yamlLines = append(yamlLines, line)
		}
	}
	yamlContent := strings.Join(yamlLines, "\n")

	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yamlContent), &parsed); err != nil {
		t.Fatalf("generated YAML is invalid: %v\n%s", err, data)
	}
}

func TestGenerate_CommentHeader(t *testing.T) {
	t.Parallel()

	catalog, err := LoadCatalog()
	if err != nil {
		t.Fatalf("LoadCatalog: %v", err)
	}

	data, err := Generate(catalog, GenerateOptions{
		GoVersion:   "1.26.1",
		LintVersion: "v2.11.2",
		Preset:      PresetMinimal,
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(data)
	if !strings.HasPrefix(output, "# Generated by fgm lint init") {
		t.Fatal("expected comment header")
	}
	if !strings.Contains(output, "preset: minimal") {
		t.Fatal("expected preset name in comment")
	}
}

func TestGenerate_InvalidGoVersion(t *testing.T) {
	t.Parallel()

	catalog, err := LoadCatalog()
	if err != nil {
		t.Fatalf("LoadCatalog: %v", err)
	}

	_, err = Generate(catalog, GenerateOptions{
		GoVersion:   "invalid",
		LintVersion: "v2.11.2",
		Preset:      PresetStandard,
	})
	if err == nil {
		t.Fatal("expected error for invalid Go version")
	}
}

func TestGenerate_InvalidPreset(t *testing.T) {
	t.Parallel()

	catalog, err := LoadCatalog()
	if err != nil {
		t.Fatalf("LoadCatalog: %v", err)
	}

	_, err = Generate(catalog, GenerateOptions{
		GoVersion:   "1.26.1",
		LintVersion: "v2.11.2",
		Preset:      "nonexistent",
	})
	if err == nil {
		t.Fatal("expected error for invalid preset")
	}
}
