package lintconfig

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// GenerateOptions configures lint config generation.
type GenerateOptions struct {
	GoVersion   string // e.g. "1.26.1"
	LintVersion string // e.g. "v2.11.2"
	Preset      string // "minimal", "standard", "strict"
	WithImports bool
	ModulePath  string // from go.mod, for gci local prefix
}

// configV2 is the top-level golangci-lint v2 configuration structure.
type configV2 struct {
	Version    string            `yaml:"version"`
	Run        runConfig         `yaml:"run"`
	Linters    lintersConfig     `yaml:"linters"`
	Formatters *formattersConfig `yaml:"formatters,omitempty"`
}

type runConfig struct {
	Timeout string `yaml:"timeout"`
}

type lintersConfig struct {
	Default string   `yaml:"default"`
	Enable  []string `yaml:"enable"`
}

type formattersConfig struct {
	Enable   []string            `yaml:"enable"`
	Settings *formattersSettings `yaml:"settings,omitempty"`
}

type formattersSettings struct {
	GCI *gciSettings `yaml:"gci,omitempty"`
}

type gciSettings struct {
	Sections []string `yaml:"sections"`
}

// Generate produces a golangci-lint v2 configuration as YAML bytes.
func Generate(catalog *Catalog, opts GenerateOptions) ([]byte, error) {
	goMinor, err := ParseGoMinor(opts.GoVersion)
	if err != nil {
		return nil, err
	}

	preset := opts.Preset
	if preset, err = NormalizePreset(preset); err != nil {
		return nil, err
	}

	linters := PresetLinters(catalog, preset, goMinor)
	if len(linters) == 0 {
		return nil, fmt.Errorf("no linters available for Go %s with preset %q", opts.GoVersion, preset)
	}

	cfg := configV2{
		Version: "2",
		Run:     runConfig{Timeout: "5m"},
		Linters: lintersConfig{
			Default: "none",
			Enable:  linters,
		},
	}

	if opts.WithImports {
		fc := buildFormattersConfig(opts.ModulePath)
		cfg.Formatters = &fc
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by fgm lint init")
	if preset != "" {
		buf.WriteString(fmt.Sprintf(" (preset: %s)", preset))
	}
	buf.WriteString("\n")
	buf.WriteString(fmt.Sprintf("# Go %s, golangci-lint %s\n", opts.GoVersion, opts.LintVersion))

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(cfg); err != nil {
		return nil, fmt.Errorf("marshal config: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("close encoder: %w", err)
	}

	return buf.Bytes(), nil
}

func buildFormattersConfig(modulePath string) formattersConfig {
	fc := formattersConfig{
		Enable: []string{"gci", "gofumpt"},
	}
	sections := []string{"standard", "default"}
	if modulePath != "" {
		sections = append(sections, fmt.Sprintf("prefix(%s)", modulePath))
	}
	fc.Settings = &formattersSettings{
		GCI: &gciSettings{Sections: sections},
	}
	return fc
}
